improve test mode

diff --git a/2021/main b/2021/main
--- a/2021/main
+++ b/2021/main
@@ -56,44 +56,49 @@ printf -v day_padded '%02d' "$day"
 input_file="input/input$day_padded"
 day_file="days/day${day_padded}_$part"
 
-# download input if does not exist
-[[ -s $input_file ]] || {
-	[[ -s .env ]] || fatal ".env file not found"
+# test mode scrapes test input if does not exist
+if [[ -n $test_mode ]]; then
+	input_file="${input_file}_test"
 
-	# shellcheck disable=SC1091
-	source .env
+	[[ -s $input_file ]] || {
+		echo "scraping test input for day $day..."
+		input=$(curl -fsS "https://adventofcode.com/$year/day/$day" |
+			sed -nE '
+			/<\/code><\/pre>/q
+			/<pre><code>/,/<\/code><\/code><\/pre>/{
+				s/<\/?(code|pre)>//g
+				p
+			}')
 
-	echo "downloading input for day $day..."
-	curl -fsS \
-		-b "session=$SESSION_ID" \
-		-o "$input_file" \
-		"https://adventofcode.com/$year/day/$day/input"
-}
+		[[ -n $input ]] || fatal 'test input not found'
+		input >"$input_file"
+	}
+else
+	# download input if does not exist
+	[[ -s $input_file ]] || {
+		[[ -s .env ]] || fatal '.env file not found'
+
+		# shellcheck disable=SC1091
+		source .env
+
+		echo "downloading input for day $day..."
+		curl -fsS \
+			-b "session=$SESSION_ID" \
+			-o "$input_file" \
+			"https://adventofcode.com/$year/day/$day/input"
+	}
+fi
+
+input=$(<"$input_file")
 
 # check day file
 [[ -s $day_file ]] || {
 	cp days/day00 "$day_file"
-	fatal "file not found: ${day_file##*/}"
+	fatal "file not found: $day_file"
 }
 
 # ensure its executable
 [[ -x $day_file ]] || chmod +x "$day_file"
-
-# load input, test mode scrapes the sample input
-input=$(<"$input_file")
-[[ -n $test_mode ]] && {
-	input=$(curl -fsS "https://adventofcode.com/$year/day/$day")
-	input=$(
-		sed -nE '
-		/<\/code><\/pre>/q
-		/<pre><code>/,/<\/code><\/code><\/pre>/{
-			s/<\/?(code|pre)>//g
-			p
-		}' <<<"$input"
-	)
-
-	[[ -n $input ]] || fatal 'test input not found'
-}
 
 # debug mode adds -x
 runner=("$day_file")
@@ -102,7 +107,7 @@ runner=("$day_file")
 echo "running $day_file"
 "${runner[@]}" <<<"$input"
 
-# watch mode keeps running every change
+# watch mode keeps running for every change
 [[ -n $watch_mode ]] && {
 	command -v inotifywait &>/dev/null || fatal 'inotifywait command not found'
 
